"use server";
/* eslint-disable @typescript-eslint/no-unused-vars -- useActionState requires the previous-state parameter. */
import { revalidatePath } from "next/cache";
import { createOption, createOptionGroup, deleteOption, deleteOptionGroup, updateOption, updateOptionGroup } from "@/data/repositories/catalog.repository";
import { RepositoryError } from "@/data/repositories/shared";
import { requireAdmin } from "@/features/admin/auth/server";
import type { AdminActionResult } from "@/features/admin/mutations/types";
import { createClient } from "@/lib/supabase/server";

const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const refresh = () => { revalidatePath("/"); revalidatePath("/admin/products/options"); };
const values = (data: FormData) => { const name = String(data.get("name") ?? "").trim(); const raw = String(data.get("sortOrder") ?? "0"); const sort_order = Number(raw); return { name, sort_order, valid: !!name && name.length <= 80 && /^\d+$/.test(raw) && Number.isSafeInteger(sort_order) }; };
const failure = (error: unknown): AdminActionResult => error instanceof RepositoryError && error.infrastructureCode === "23505" ? { ok: false, message: "Já existe um item com esse nome neste nível." } : (console.error("Falha ao alterar catálogo.", error instanceof Error ? { name: error.name } : undefined), { ok: false, message: "Não foi possível concluir a alteração." });

export async function saveGroupAction(id: string | null, categoryId: string, _state: AdminActionResult, data: FormData): Promise<AdminActionResult> { await requireAdmin(); if (!uuid.test(categoryId) || (id && !uuid.test(id))) return { ok: false, message: "Identificador inválido." }; const parsed = values(data); if (!parsed.valid) return { ok: false, message: "Informe nome e ordem válidos." }; try { const payload = { category_id: categoryId, name: parsed.name, sort_order: parsed.sort_order, is_required: data.get("isRequired") === "on", is_active: data.get("isActive") === "on" }; const client = await createClient(); if (id) await updateOptionGroup(client, id, payload); else await createOptionGroup(client, payload); refresh(); return { ok: true, message: id ? "Grupo atualizado." : "Grupo criado." }; } catch (error) { return failure(error); } }
export async function deleteGroupAction(id: string, _state: AdminActionResult): Promise<AdminActionResult> { await requireAdmin(); if (!uuid.test(id)) return { ok: false, message: "Grupo inválido." }; try { const client = await createClient(); const { count, error } = await client.from("product_options").select("id", { count: "exact", head: true }).eq("group_id", id); if (error) throw error; if (count) return { ok: false, message: "Desative o grupo ou remova suas opções antes de excluir." }; await deleteOptionGroup(client, id); refresh(); return { ok: true, message: "Grupo excluído." }; } catch (error) { return failure(error); } }
export async function saveOptionAction(id: string | null, groupId: string, _state: AdminActionResult, data: FormData): Promise<AdminActionResult> { await requireAdmin(); if (!uuid.test(groupId) || (id && !uuid.test(id))) return { ok: false, message: "Identificador inválido." }; const parsed = values(data); if (!parsed.valid) return { ok: false, message: "Informe nome e ordem válidos." }; try { const payload = { group_id: groupId, name: parsed.name, sort_order: parsed.sort_order, is_active: data.get("isActive") === "on" }; const client = await createClient(); if (id) await updateOption(client, id, payload); else await createOption(client, payload); refresh(); return { ok: true, message: id ? "Opção atualizada." : "Opção criada." }; } catch (error) { return failure(error); } }
export async function deleteOptionAction(id: string, _state: AdminActionResult): Promise<AdminActionResult> { await requireAdmin(); if (!uuid.test(id)) return { ok: false, message: "Opção inválida." }; try { await deleteOption(await createClient(), id); refresh(); return { ok: true, message: "Opção excluída." }; } catch (error) { return failure(error); } }
