"use client";
import { useActionState, useState } from "react";
import type { AdminCatalogCategory, OptionGroupRow, OptionRow } from "@/data/repositories/catalog.repository";
import { FormFeedback } from "@/features/admin/components/form-feedback";
import { initialAdminActionResult } from "@/features/admin/mutations/types";
import { deleteGroupAction, deleteOptionAction, saveGroupAction, saveOptionAction } from "./actions";

const field = "field mt-1";
function ItemFields({ item, group = false }: { item?: OptionGroupRow | OptionRow; group?: boolean }) { return <div className="grid gap-3 sm:grid-cols-[1fr_7rem_auto_auto]"><label className="text-sm font-extrabold text-olive">Nome<input className={field} name="name" defaultValue={item?.name} maxLength={80} required /></label><label className="text-sm font-extrabold text-olive">Ordem<input className={field} name="sortOrder" type="number" min="0" defaultValue={item?.sort_order ?? 0} required /></label>{group && <label className="flex items-center gap-2 font-bold text-olive"><input name="isRequired" type="checkbox" defaultChecked={(item as OptionGroupRow | undefined)?.is_required ?? true} />Obrigatório</label>}<label className="flex items-center gap-2 font-bold text-olive"><input name="isActive" type="checkbox" defaultChecked={item?.is_active ?? true} />Ativo</label></div>; }
function DeleteButton({ action, label }: { action: (state: typeof initialAdminActionResult) => Promise<typeof initialAdminActionResult>; label: string }) { const [state, formAction, pending] = useActionState(action, initialAdminActionResult); const [confirm, setConfirm] = useState(false); return <div>{confirm ? <div className="flex gap-2"><form action={formAction}><button className="btn bg-red-700 text-white" disabled={pending}>{pending ? "Excluindo…" : "Confirmar exclusão"}</button></form><button className="btn btn-secondary" onClick={() => setConfirm(false)}>Cancelar</button></div> : <button className="text-sm font-bold text-red-700" onClick={() => setConfirm(true)}>{label}</button>}<FormFeedback state={state} /></div>; }
function OptionForm({ groupId, option }: { groupId: string; option?: OptionRow }) { const [state, action, pending] = useActionState(saveOptionAction.bind(null, option?.id ?? null, groupId), initialAdminActionResult); return <div className="rounded-xl border border-stone-200 bg-stone-50 p-3"><form action={action} className="space-y-3"><ItemFields item={option} /><FormFeedback state={state} /><button className="btn btn-secondary" disabled={pending}>{pending ? "Salvando…" : option ? "Salvar opção" : "Adicionar opção"}</button></form>{option && <div className="mt-2"><DeleteButton action={deleteOptionAction.bind(null, option.id)} label="Excluir opção" /></div>}</div>; }
function GroupCard({ categoryId, group }: { categoryId: string; group: AdminCatalogCategory["groups"][number] }) { const [state, action, pending] = useActionState(saveGroupAction.bind(null, group.id, categoryId), initialAdminActionResult); return <article className="rounded-2xl border border-stone-200 bg-white p-4"><form action={action} className="space-y-3"><ItemFields item={group} group /><FormFeedback state={state} /><button className="btn btn-primary" disabled={pending}>{pending ? "Salvando…" : "Salvar grupo"}</button></form><div className="mt-4 space-y-3 border-t border-stone-200 pt-4"><h4 className="font-black text-olive">Opções</h4>{group.options.map((option) => <OptionForm key={option.id} groupId={group.id} option={option} />)}<OptionForm groupId={group.id} /></div><div className="mt-4"><DeleteButton action={deleteGroupAction.bind(null, group.id)} label="Excluir grupo vazio" /></div></article>; }
function NewGroup({ categoryId }: { categoryId: string }) { const [state, action, pending] = useActionState(saveGroupAction.bind(null, null, categoryId), initialAdminActionResult); return <form action={action} className="space-y-3 rounded-2xl border border-dashed border-brand/40 bg-orange-50 p-4"><h3 className="font-black text-olive">Novo grupo</h3><ItemFields group /><FormFeedback state={state} /><button className="btn btn-primary" disabled={pending}>{pending ? "Criando…" : "Criar grupo"}</button></form>; }
export function CatalogManager({ categories }: { categories: AdminCatalogCategory[] }) { return <div className="space-y-7">{categories.map((category) => <section key={category.id} className="space-y-4"><header><h2 className="text-2xl font-black text-olive">{category.name}</h2><p className="text-sm font-semibold text-stone-600">{category.description || "Sem descrição"} · {category.is_active ? "ativa" : "inativa"}</p></header>{category.groups.map((group) => <GroupCard key={group.id} categoryId={category.id} group={group} />)}<NewGroup categoryId={category.id} /></section>)}</div>; }
