import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ requireAdmin: vi.fn(), revalidatePath: vi.fn(), createClient: vi.fn(async () => ({})), createFaq: vi.fn(), updateFaq: vi.fn(), toggleFaqPublished: vi.fn(), deleteFaq: vi.fn(), getAdminFaq: vi.fn() }));
vi.mock("next/cache", () => ({ revalidatePath: mocks.revalidatePath })); vi.mock("@/features/admin/auth/server", () => ({ requireAdmin: mocks.requireAdmin })); vi.mock("@/lib/supabase/server", () => ({ createClient: mocks.createClient })); vi.mock("@/data/repositories/faqs.repository", () => ({ createFaq: mocks.createFaq, updateFaq: mocks.updateFaq, toggleFaqPublished: mocks.toggleFaqPublished, deleteFaq: mocks.deleteFaq, getAdminFaq: mocks.getAdminFaq }));
import { createFaqAction, deleteFaqAction, toggleFaqAction, updateFaqAction } from "./actions";
const id = "20000000-0000-4000-8000-000000000001"; const previous = { ok: true as const, message: "" };
function form() { const data = new FormData(); Object.entries({ question: "Quando abre?", answer: "Às nove.", sortOrder: "4", isPublished: "on" }).forEach(([key, value]) => data.set(key, value)); return data; }
describe("FAQ actions", () => { beforeEach(() => { vi.clearAllMocks(); mocks.getAdminFaq.mockResolvedValue({ id }); });
  it("creates with a whitelist and revalidates all paths", async () => { await expect(createFaqAction(previous, form())).resolves.toMatchObject({ ok: true }); expect(mocks.createFaq).toHaveBeenCalledWith({}, { question: "Quando abre?", answer: "Às nove.", sort_order: 4, is_published: true }); for (const path of ["/", "/admin", "/admin/faqs"]) expect(mocks.revalidatePath).toHaveBeenCalledWith(path); });
  it("updates, publishes, unpublishes and deletes existing items", async () => { await updateFaqAction(id, previous, form()); await toggleFaqAction(id, false, previous); await toggleFaqAction(id, true, previous); await deleteFaqAction(id, previous); expect(mocks.updateFaq).toHaveBeenCalledOnce(); expect(mocks.toggleFaqPublished).toHaveBeenNthCalledWith(1, {}, id, false); expect(mocks.toggleFaqPublished).toHaveBeenNthCalledWith(2, {}, id, true); expect(mocks.deleteFaq).toHaveBeenCalledOnce(); });
  it("handles missing items and authorization failure", async () => { mocks.getAdminFaq.mockResolvedValue(null); await expect(deleteFaqAction(id, previous)).resolves.toMatchObject({ ok: false }); mocks.requireAdmin.mockRejectedValueOnce(new Error("NEXT_REDIRECT")); await expect(createFaqAction(previous, form())).rejects.toThrow("NEXT_REDIRECT"); });
});
