"use client";
import { useActionState, useState } from "react";
import type { FaqRow } from "@/data/repositories/faqs.repository";
import { FieldError, FormFeedback } from "@/features/admin/components/form-feedback";
import { initialAdminActionResult } from "@/features/admin/mutations/types";
import { createFaqAction, deleteFaqAction, toggleFaqAction, updateFaqAction } from "./actions";
const inputClass = "field mt-1";
function Fields({ faq, state }: { faq?: FaqRow; state: typeof initialAdminActionResult }) { return <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-extrabold text-olive sm:col-span-2">Pergunta<input className={inputClass} name="question" defaultValue={faq?.question} maxLength={300} required /><FieldError state={state} name="question" /></label><label className="text-sm font-extrabold text-olive sm:col-span-2">Resposta<textarea className={`${inputClass} min-h-32`} name="answer" defaultValue={faq?.answer} maxLength={5000} required /><FieldError state={state} name="answer" /></label><label className="text-sm font-extrabold text-olive">Ordem<input className={inputClass} name="sortOrder" type="number" min="0" step="1" defaultValue={faq?.sort_order ?? 0} required /><FieldError state={state} name="sortOrder" /></label><label className="flex min-h-11 items-center gap-2 self-end rounded-xl bg-stone-50 px-3 font-extrabold text-olive"><input name="isPublished" type="checkbox" defaultChecked={faq?.is_published ?? true} />Publicada no site</label></div>; }
export function NewFaqForm() { const [state, action, pending] = useActionState(createFaqAction, initialAdminActionResult); return <section id="nova-faq" className="mb-6 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6"><h2 className="mb-4 text-xl font-black text-olive">Nova pergunta</h2><form action={action} className="space-y-4"><Fields state={state} /><FormFeedback state={state} /><button className="btn btn-primary w-full sm:w-auto" disabled={pending}>{pending ? "Criando…" : "Criar FAQ"}</button></form></section>; }
export function FaqCard({ faq }: { faq: FaqRow }) { const [state, action, pending] = useActionState(updateFaqAction.bind(null, faq.id), initialAdminActionResult); const [toggleState, toggleAction, toggling] = useActionState(toggleFaqAction.bind(null, faq.id, !faq.is_published), initialAdminActionResult); const [deleteState, deleteAction, deleting] = useActionState(deleteFaqAction.bind(null, faq.id), initialAdminActionResult); const [confirming, setConfirming] = useState(false); return <article className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6"><div className="mb-4 flex flex-wrap items-start justify-between gap-2"><div><h2 className="text-xl font-black text-olive">{faq.question}</h2><p className="text-sm font-bold text-stone-500">Ordem {faq.sort_order}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${faq.is_published ? "bg-green-100 text-green-800" : "bg-stone-200 text-stone-700"}`}>{faq.is_published ? "Publicada" : "Rascunho"}</span></div><form action={action} className="space-y-4"><Fields faq={faq} state={state} /><FormFeedback state={state} /><button className="btn btn-primary w-full sm:w-auto" disabled={pending}>{pending ? "Salvando…" : "Salvar edição"}</button></form><div className="my-4 h-px bg-stone-200" /><div className="flex flex-wrap gap-2"><form action={toggleAction}><button className="btn btn-secondary min-h-11" disabled={toggling}>{toggling ? "Alterando…" : faq.is_published ? "Despublicar" : "Publicar"}</button></form>{confirming ? <><form action={deleteAction}><button className="btn min-h-11 bg-red-700 text-white" disabled={deleting}>{deleting ? "Excluindo…" : "Confirmar exclusão"}</button></form><button type="button" className="btn btn-secondary" onClick={() => setConfirming(false)}>Cancelar</button></> : <button type="button" className="btn border border-red-200 bg-white text-red-700" onClick={() => setConfirming(true)}>Excluir</button>}</div><FormFeedback state={toggleState.message ? toggleState : deleteState} />{confirming && <p role="alert" className="mt-2 text-sm font-bold text-red-700">Excluir esta FAQ permanentemente?</p>}</article>; }
