import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ requireAdmin: vi.fn(), revalidatePath: vi.fn(), createService: vi.fn(), updateService: vi.fn(), toggleService: vi.fn(), deleteService: vi.fn(), getAdminService: vi.fn(), createClient: vi.fn(() => Promise.resolve({})) }));
vi.mock("next/cache", () => ({ revalidatePath: mocks.revalidatePath })); vi.mock("@/features/admin/auth/server", () => ({ requireAdmin: mocks.requireAdmin })); vi.mock("@/lib/supabase/server", () => ({ createClient: mocks.createClient })); vi.mock("@/data/repositories/services.repository", () => ({ createService: mocks.createService, updateService: mocks.updateService, toggleService: mocks.toggleService, deleteService: mocks.deleteService, getAdminService: mocks.getAdminService }));
import { createServiceAction, deleteServiceAction, toggleServiceAction, updateServiceAction } from "./actions";
const previous = { ok: true as const, message: "" }; const id = "20000000-0000-4000-8000-000000000001";
function form() { const data = new FormData(); Object.entries({ name: "Banho", iconKey: "bath", pricingType: "fixed", price: "50", sortOrder: "1", isActive: "on", isBookable: "on", isFeatured: "on" }).forEach(([k, v]) => data.set(k, v)); return data; }
describe("service actions", () => { beforeEach(() => { vi.clearAllMocks(); mocks.requireAdmin.mockResolvedValue({ id: "admin" }); mocks.getAdminService.mockResolvedValue({ id, icon_key: "bath" }); });
  it("creates and revalidates home/admin", async () => { await expect(createServiceAction(previous, form())).resolves.toMatchObject({ ok: true }); expect(mocks.createService).toHaveBeenCalledWith({}, expect.objectContaining({ price: "50.00", is_bookable: true })); for (const path of ["/", "/admin/services", "/admin"]) expect(mocks.revalidatePath).toHaveBeenCalledWith(path); });
  it("updates pricing, toggles and deletes", async () => { await updateServiceAction(id, previous, form()); await toggleServiceAction(id, false, previous); await deleteServiceAction(id, previous); expect(mocks.updateService).toHaveBeenCalledOnce(); expect(mocks.toggleService).toHaveBeenCalledWith({}, id, false); expect(mocks.deleteService).toHaveBeenCalledOnce(); });
  it("handles missing service", async () => { mocks.getAdminService.mockResolvedValue(null); await expect(toggleServiceAction(id, false, previous)).resolves.toMatchObject({ message: "Serviço não encontrado." }); });
  it("does not write without admin", async () => { mocks.requireAdmin.mockRejectedValue(new Error("NEXT_REDIRECT")); await expect(createServiceAction(previous, form())).rejects.toThrow("NEXT_REDIRECT"); expect(mocks.createService).not.toHaveBeenCalled(); });
});
