"use client";

import { useActionState, useState } from "react";
import type { ServiceRow } from "@/data/repositories/services.repository";
import { FieldError, FormFeedback, fieldAccessibility } from "@/features/admin/components/form-feedback";
import { initialAdminActionResult } from "@/features/admin/mutations/types";
import { SERVICE_ICON_OPTIONS, isSupportedServiceIcon } from "@/lib/service-icons";
import { createServiceAction, deleteServiceAction, toggleServiceAction, updateServiceAction } from "./actions";

const inputClass = "field mt-1";
function ServiceFields({ service, state }: { service?: ServiceRow; state: typeof initialAdminActionResult }) { const unknownIcon = service?.icon_key && !isSupportedServiceIcon(service.icon_key); const id = (name: string) => `service-${service?.id ?? "new"}-${name}`; const a11y = (name: string) => fieldAccessibility(state, name, id(name)); const error = (name: string) => <FieldError state={state} name={name} fieldId={id(name)} />; return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2">
  <label className="text-sm font-extrabold text-olive">Nome<input {...a11y("name")} className={inputClass} name="name" defaultValue={service?.name} maxLength={120} required />{error("name")}</label>
  <label className="text-sm font-extrabold text-olive">Slug <span className="font-semibold text-stone-500">(opcional no cadastro)</span><input {...a11y("slug")} className={inputClass} name="slug" defaultValue={service?.slug} maxLength={120} placeholder="gerado pelo nome" />{error("slug")}</label>
  <label className="text-sm font-extrabold text-olive">Ícone<select {...a11y("iconKey")} className={inputClass} name="iconKey" defaultValue={service?.icon_key ?? "bath"}>{unknownIcon && <option value={service.icon_key}>{service.icon_key} (desconhecido — atual)</option>}{SERVICE_ICON_OPTIONS.map((option) => <option key={option.key} value={option.key}>{option.label}</option>)}</select>{unknownIcon && <p className="mt-1 text-xs font-bold text-amber-800">Chave não reconhecida. Ela será preservada se você não trocar a seleção.</p>}{error("iconKey")}</label>
  <label className="text-sm font-extrabold text-olive">Tipo de preço<select {...a11y("pricingType")} className={inputClass} name="pricingType" defaultValue={service?.pricing_type ?? "quote"}><option value="fixed">Preço fixo</option><option value="starting_at">A partir de</option><option value="quote">Sob consulta</option></select>{error("pricingType")}</label>
  <label className="text-sm font-extrabold text-olive">Preço fixo<input {...a11y("price")} className={inputClass} name="price" inputMode="decimal" defaultValue={service?.price ?? ""} placeholder="129,90" />{error("price")}</label>
  <label className="text-sm font-extrabold text-olive">Preço “a partir de”<input {...a11y("priceFrom")} className={inputClass} name="priceFrom" inputMode="decimal" defaultValue={service?.price_from ?? ""} placeholder="89,90" />{error("priceFrom")}</label>
  <label className="text-sm font-extrabold text-olive">Ordem<input {...a11y("sortOrder")} className={inputClass} name="sortOrder" type="number" min="0" step="1" defaultValue={service?.sort_order ?? 0} required />{error("sortOrder")}</label>
  <label className="text-sm font-extrabold text-olive sm:col-span-2">Descrição<textarea {...a11y("description")} className={`${inputClass} min-h-28`} name="description" defaultValue={service?.description} maxLength={4000} />{error("description")}</label>
  <div className="grid gap-2 sm:col-span-2 sm:grid-cols-2"><label className="flex min-h-11 items-center gap-2 rounded-xl bg-stone-50 px-3 font-extrabold text-olive"><input name="isActive" type="checkbox" defaultChecked={service?.is_active ?? true} />Ativo no site</label><label className="flex min-h-11 items-center gap-2 rounded-xl bg-stone-50 px-3 font-extrabold text-olive"><input name="isBookable" type="checkbox" defaultChecked={service?.is_bookable ?? true} />Disponível no atendimento</label></div><p className="text-xs font-semibold text-stone-500 sm:col-span-2">“Disponível no atendimento” permite selecionar este serviço no formulário. Ao desativar o serviço, essa opção também é desligada.</p>
  </div></div>; }
export function NewServiceForm() { const [state, action, pending] = useActionState(createServiceAction, initialAdminActionResult); return <section id="novo-servico" className="mb-6 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6"><h2 className="mb-4 text-xl font-black text-olive">Novo serviço</h2><form action={action} className="space-y-4"><ServiceFields state={state} /><FormFeedback state={state} /><button className="btn btn-primary w-full sm:w-auto" disabled={pending}>{pending ? "Criando…" : "Criar serviço"}</button></form></section>; }
function ServiceActions({ service }: { service: ServiceRow }) { const [toggleState, toggleAction, togglePending] = useActionState(toggleServiceAction.bind(null, service.id, !service.is_active), initialAdminActionResult); const [deleteState, deleteAction, deletePending] = useActionState(deleteServiceAction.bind(null, service.id), initialAdminActionResult); const [confirming, setConfirming] = useState(false); return <div className="space-y-3"><div className="flex flex-wrap gap-2"><form action={toggleAction}><button className="btn btn-secondary min-h-11" disabled={togglePending}>{togglePending ? "Alterando…" : service.is_active ? "Desativar" : "Ativar"}</button></form>{confirming ? <><form action={deleteAction}><button className="btn min-h-11 bg-red-700 text-white" disabled={deletePending}>{deletePending ? "Excluindo…" : `Excluir ${service.name}`}</button></form><button type="button" className="btn btn-secondary min-h-11" onClick={() => setConfirming(false)}>Cancelar</button></> : <button type="button" className="btn min-h-11 border border-red-200 bg-white text-red-700" onClick={() => setConfirming(true)}>Excluir</button>}</div><FormFeedback state={toggleState.message ? toggleState : deleteState} />{confirming && <p role="alert" className="text-sm font-bold text-red-700">Confirmar exclusão permanente de “{service.name}”? Esta ação não pode ser desfeita.</p>}</div>; }
export function ServiceCard({ service }: { service: ServiceRow }) { const [state, action, pending] = useActionState(updateServiceAction.bind(null, service.id), initialAdminActionResult); const pricing = service.pricing_type === "fixed" ? `R$ ${Number(service.price).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}` : service.pricing_type === "starting_at" ? `A partir de R$ ${Number(service.price_from).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}` : "Sob consulta"; return <article className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6"><div className="mb-4 flex flex-wrap items-start justify-between gap-2"><div><h2 className="text-xl font-black text-olive">{service.name}</h2><p className="text-sm font-bold text-stone-500">{pricing} · {service.is_bookable ? "Agendável" : "Não agendável"} · ordem {service.sort_order}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${service.is_active ? "bg-green-100 text-green-800" : "bg-stone-200 text-stone-700"}`}>{service.is_active ? "Ativo" : "Inativo"}</span></div><form action={action} className="space-y-4"><ServiceFields service={service} state={state} /><FormFeedback state={state} /><button className="btn btn-primary w-full sm:w-auto" disabled={pending}>{pending ? "Salvando…" : "Salvar edição"}</button></form><div className="my-4 h-px bg-stone-200" /><ServiceActions service={service} /></article>; }
