import { beforeEach, describe, expect, it, vi } from "vitest";
import { RepositoryError } from "@/data/repositories/shared";
const mocks = vi.hoisted(() => ({ requireAdmin: vi.fn(), revalidatePath: vi.fn(), listAdminCategories: vi.fn(), createProduct: vi.fn(), updateProduct: vi.fn(), updateProductImagePath: vi.fn(), toggleProduct: vi.fn(), deleteProduct: vi.fn(), getAdminProduct: vi.fn(), verifyProductUpload: vi.fn(), removeProductImageFile: vi.fn(), createClient: vi.fn(() => Promise.resolve({})) }));
vi.mock("next/cache", () => ({ revalidatePath: mocks.revalidatePath })); vi.mock("@/features/admin/auth/server", () => ({ requireAdmin: mocks.requireAdmin })); vi.mock("@/lib/supabase/server", () => ({ createClient: mocks.createClient })); vi.mock("@/lib/storage/admin-site-assets", () => ({ PRODUCT_PATH_PATTERN: /^products\/[0-9a-f-]+\.(?:webp|png)$/i, verifyProductUpload: mocks.verifyProductUpload, removeProductImageFile: mocks.removeProductImageFile })); vi.mock("@/data/repositories/categories.repository", () => ({ listAdminCategories: mocks.listAdminCategories })); vi.mock("@/data/repositories/products.repository", () => ({ createProduct: mocks.createProduct, updateProduct: mocks.updateProduct, updateProductImagePath: mocks.updateProductImagePath, toggleProduct: mocks.toggleProduct, deleteProduct: mocks.deleteProduct, getAdminProduct: mocks.getAdminProduct }));
import { createProductAction, deleteProductAction, removeProductImageAction, replaceProductImageAction, toggleProductAction, updateProductAction } from "./actions";
const previous = { ok: true as const, message: "" }; const id = "20000000-0000-4000-8000-000000000001"; const categoryId = "30000000-0000-4000-8000-000000000001";
function form() { const data = new FormData(); Object.entries({ name: "Ração", categoryId, price: "10,50", sortOrder: "3", isActive: "on", isFeatured: "on" }).forEach(([k, v]) => data.set(k, v)); return data; }
describe("product actions", () => { beforeEach(() => { vi.clearAllMocks(); mocks.requireAdmin.mockResolvedValue({ id: "admin" }); mocks.listAdminCategories.mockResolvedValue([{ id: categoryId, is_active: true }]); mocks.getAdminProduct.mockResolvedValue({ id, category_id: categoryId }); });
  it("creates with whitelist and revalidates public/admin paths", async () => { await expect(createProductAction(previous, form())).resolves.toMatchObject({ ok: true }); expect(mocks.createProduct).toHaveBeenCalledWith({}, expect.objectContaining({ price: "10.50", is_featured: true })); for (const path of ["/", "/admin/products", "/admin"]) expect(mocks.revalidatePath).toHaveBeenCalledWith(path); });
  it("rejects an absent category", async () => { mocks.listAdminCategories.mockResolvedValue([]); await expect(createProductAction(previous, form())).resolves.toMatchObject({ ok: false, fieldErrors: { categoryId: expect.any(String) } }); expect(mocks.createProduct).not.toHaveBeenCalled(); });
  it("rejects an inactive category for create but preserves the current one on update", async () => { mocks.listAdminCategories.mockResolvedValue([{ id: categoryId, is_active: false }]); await expect(createProductAction(previous, form())).resolves.toMatchObject({ ok: false }); await expect(updateProductAction(id, previous, form())).resolves.toMatchObject({ ok: true }); });
  it("maps duplicate slug safely", async () => { mocks.createProduct.mockRejectedValue(new RepositoryError("products", "write", "23505")); await expect(createProductAction(previous, form())).resolves.toMatchObject({ ok: false, fieldErrors: { slug: expect.any(String) } }); });
  it("updates, toggles and deletes existing products", async () => { await updateProductAction(id, previous, form()); await toggleProductAction(id, false, previous); await deleteProductAction(id, previous); expect(mocks.updateProduct).toHaveBeenCalledOnce(); expect(mocks.toggleProduct).toHaveBeenCalledWith({}, id, false); expect(mocks.deleteProduct).toHaveBeenCalledOnce(); });
  it("handles a missing item", async () => { mocks.getAdminProduct.mockResolvedValue(null); await expect(deleteProductAction(id, previous)).resolves.toMatchObject({ message: "Produto não encontrado." }); });
  it("replaces an image before removing the old file", async () => { const oldPath = "products/10000000-0000-4000-8000-000000000001.webp"; const newPath = "products/10000000-0000-4000-8000-000000000002.webp"; mocks.getAdminProduct.mockResolvedValue({ id, category_id: categoryId, image_path: oldPath }); await expect(replaceProductImageAction(id, newPath)).resolves.toMatchObject({ ok: true }); expect(mocks.verifyProductUpload).toHaveBeenCalledWith({}, newPath); expect(mocks.updateProductImagePath).toHaveBeenCalledWith({}, id, newPath); expect(mocks.removeProductImageFile).toHaveBeenCalledWith({}, oldPath); });
  it("removes the new file when persisting its path fails", async () => { const newPath = "products/10000000-0000-4000-8000-000000000002.webp"; mocks.updateProductImagePath.mockRejectedValueOnce(new Error("write")); await expect(replaceProductImageAction(id, newPath)).resolves.toMatchObject({ ok: false }); expect(mocks.removeProductImageFile).toHaveBeenCalledWith({}, newPath); });
  it("clears image_path before deleting the product file", async () => { const oldPath = "products/10000000-0000-4000-8000-000000000001.webp"; mocks.getAdminProduct.mockResolvedValue({ id, category_id: categoryId, image_path: oldPath }); await expect(removeProductImageAction(id)).resolves.toMatchObject({ ok: true }); expect(mocks.updateProductImagePath).toHaveBeenCalledWith({}, id, null); expect(mocks.removeProductImageFile).toHaveBeenCalledWith({}, oldPath); });
  it("does not write when authorization fails", async () => { mocks.requireAdmin.mockRejectedValue(new Error("NEXT_REDIRECT")); await expect(createProductAction(previous, form())).rejects.toThrow("NEXT_REDIRECT"); expect(mocks.createProduct).not.toHaveBeenCalled(); });
});
