"use client";

import { useActionState, useEffect, useRef, useState } from "react";
import Image from "next/image";
import type { AdminCategory } from "@/data/repositories/categories.repository";
import type { AdminProduct } from "@/data/repositories/products.repository";
import { FieldError, FormFeedback } from "@/features/admin/components/form-feedback";
import { initialAdminActionResult } from "@/features/admin/mutations/types";
import type { AdminActionResult } from "@/features/admin/mutations/types";
import { optimizeImage, optimizedFilename, type OptimizedImage } from "@/lib/images/optimize-image";
import { SITE_ASSETS_BUCKET } from "@/lib/storage/site-assets";
import { createClient } from "@/lib/supabase/client";
import { createProductAction, deleteProductAction, removeProductImageAction, replaceProductImageAction, toggleProductAction, updateProductAction } from "./actions";

const inputClass = "field mt-1";
function ProductFields({ product, categories, state }: { product?: AdminProduct; categories: AdminCategory[]; state: typeof initialAdminActionResult }) {
  const selectable = categories.filter((category) => category.is_active || category.id === product?.category_id);
  return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2">
    <label className="text-sm font-extrabold text-olive">Nome<input className={inputClass} name="name" defaultValue={product?.name} maxLength={120} required /><FieldError state={state} name="name" /></label>
    <label className="text-sm font-extrabold text-olive">Slug <span className="font-semibold text-stone-500">(opcional no cadastro)</span><input className={inputClass} name="slug" defaultValue={product?.slug} maxLength={120} placeholder="gerado pelo nome" /><FieldError state={state} name="slug" /></label>
    <label className="text-sm font-extrabold text-olive">Categoria<select className={inputClass} name="categoryId" defaultValue={product?.category_id ?? ""} required><option value="">Selecione</option>{selectable.map((category) => <option key={category.id} value={category.id}>{category.name}{category.is_active ? "" : " (inativa — atual)"}</option>)}</select><FieldError state={state} name="categoryId" /></label>
    <label className="text-sm font-extrabold text-olive">Preço em reais <span className="font-semibold text-stone-500">(opcional)</span><input className={inputClass} name="price" inputMode="decimal" defaultValue={product?.price ?? ""} placeholder="129,90" /><FieldError state={state} name="price" /></label>
    <label className="text-sm font-extrabold text-olive sm:col-span-2">Descrição<textarea className={`${inputClass} min-h-28`} name="description" defaultValue={product?.description} maxLength={4000} /><FieldError state={state} name="description" /></label>
    <label className="text-sm font-extrabold text-olive">Ordem<input className={inputClass} name="sortOrder" type="number" min="0" step="1" defaultValue={product?.sort_order ?? 0} required /><FieldError state={state} name="sortOrder" /></label>
    <div className="grid gap-2"><label className="flex min-h-11 items-center gap-2 rounded-xl bg-stone-50 px-3 font-extrabold text-olive"><input name="isActive" type="checkbox" defaultChecked={product?.is_active ?? true} />Ativo no site</label><label className="flex min-h-11 items-center gap-2 rounded-xl bg-stone-50 px-3 font-extrabold text-olive"><input name="isFeatured" type="checkbox" defaultChecked={product?.is_featured ?? false} />Produto em destaque</label></div>
  </div></div>;
}
export function NewProductForm({ categories }: { categories: AdminCategory[] }) { const [state, action, pending] = useActionState(createProductAction, initialAdminActionResult); return <section id="novo-produto" className="mb-6 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6"><h2 className="mb-4 text-xl font-black text-olive">Novo produto</h2><form action={action} className="space-y-4"><ProductFields categories={categories} state={state} /><p className="text-sm font-semibold text-stone-600">Após criar o produto, use o editor dele abaixo para enviar a imagem própria.</p><FormFeedback state={state} /><button className="btn btn-primary w-full sm:w-auto" disabled={pending || !categories.some((c) => c.is_active)}>{pending ? "Criando…" : "Criar produto"}</button>{!categories.some((c) => c.is_active) && <p className="text-sm font-bold text-amber-800">Ative ou crie uma categoria antes de cadastrar produtos.</p>}</form></section>; }

function ProductImageEditor({ product, imageUrl }: { product: AdminProduct; imageUrl: string | null }) {
  const [optimized, setOptimized] = useState<OptimizedImage | null>(null); const [preview, setPreview] = useState<string | null>(null); const previewRef = useRef<string | null>(null); const [state, setState] = useState<AdminActionResult>(initialAdminActionResult); const [pending, setPending] = useState(false);
  useEffect(() => () => { if (previewRef.current) URL.revokeObjectURL(previewRef.current); }, []);
  async function select(file?: File) { if (previewRef.current) URL.revokeObjectURL(previewRef.current); previewRef.current = null; setPreview(null); setOptimized(null); setState(initialAdminActionResult); if (!file) return; try { const value = await optimizeImage(file); const url = URL.createObjectURL(value.file); previewRef.current = url; setPreview(url); setOptimized(value); } catch (error) { setState({ ok: false, message: error instanceof Error ? error.message : "Não foi possível otimizar a imagem." }); } }
  async function upload() { if (!optimized) return; setPending(true); setState({ ok: true, message: "Enviando…" }); const path = optimizedFilename(optimized.mimeType, crypto.randomUUID(), "products"); try { const { error } = await createClient().storage.from(SITE_ASSETS_BUCKET).upload(path, optimized.file, { contentType: optimized.mimeType, upsert: false }); if (error) throw new Error("Não foi possível enviar a imagem. Confirme sua sessão e tente novamente."); setState(await replaceProductImageAction(product.id, path)); } catch (error) { setState({ ok: false, message: error instanceof Error ? error.message : "Falha no envio." }); } finally { setPending(false); } }
  async function remove() { setPending(true); try { setState(await removeProductImageAction(product.id)); } finally { setPending(false); } }
  return <section className="space-y-3 rounded-xl bg-stone-50 p-3"><h3 className="font-black text-olive">Imagem do produto</h3>{imageUrl && <Image src={imageUrl} width={320} height={220} alt={`Imagem atual de ${product.name}`} className="h-40 w-full rounded-lg object-cover sm:w-64" />}{!imageUrl && <p className="text-sm font-semibold text-stone-600">Sem imagem: o site exibe o placeholder do produto.</p>}<label className="block text-sm font-extrabold text-olive">Selecionar nova imagem<input className={inputClass} type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={pending} onChange={(event) => void select(event.target.files?.[0])} /></label>{preview && <Image src={preview} width={320} height={220} alt="Prévia da nova imagem do produto" unoptimized className="h-40 w-full rounded-lg object-contain sm:w-64" />}<p className="text-xs font-semibold text-stone-500">JPEG, PNG, WebP ou AVIF; otimização automática para até 1920 px.</p><div className="flex flex-wrap gap-2"><button type="button" className="btn btn-secondary" disabled={pending || !optimized} onClick={() => void upload()}>{pending ? "Processando…" : imageUrl ? "Substituir imagem" : "Enviar imagem"}</button>{imageUrl && <button type="button" className="btn border border-red-200 bg-white text-red-700" disabled={pending} onClick={() => void remove()}>Remover imagem</button>}</div><FormFeedback state={state} /></section>;
}
function ProductActions({ product }: { product: AdminProduct }) { const [toggleState, toggleAction, togglePending] = useActionState(toggleProductAction.bind(null, product.id, !product.is_active), initialAdminActionResult); const [deleteState, deleteAction, deletePending] = useActionState(deleteProductAction.bind(null, product.id), initialAdminActionResult); const [confirming, setConfirming] = useState(false); return <div className="space-y-3"><div className="flex flex-wrap gap-2"><form action={toggleAction}><button className="btn btn-secondary min-h-11" disabled={togglePending}>{togglePending ? "Alterando…" : product.is_active ? "Desativar" : "Ativar"}</button></form>{confirming ? <><form action={deleteAction}><button className="btn min-h-11 bg-red-700 text-white" disabled={deletePending}>{deletePending ? "Excluindo…" : `Excluir ${product.name}`}</button></form><button type="button" className="btn btn-secondary min-h-11" onClick={() => setConfirming(false)}>Cancelar</button></> : <button type="button" className="btn min-h-11 border border-red-200 bg-white text-red-700" onClick={() => setConfirming(true)}>Excluir</button>}</div><FormFeedback state={toggleState.message ? toggleState : deleteState} />{confirming && <p role="alert" className="text-sm font-bold text-red-700">Confirmar exclusão permanente de “{product.name}”? Esta ação não pode ser desfeita.</p>}</div>; }
export function ProductCard({ product, categories, imageUrl }: { product: AdminProduct; categories: AdminCategory[]; imageUrl: string | null }) { const [state, action, pending] = useActionState(updateProductAction.bind(null, product.id), initialAdminActionResult); return <article className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6"><div className="mb-4 flex flex-wrap items-start justify-between gap-2"><div><h2 className="text-xl font-black text-olive">{product.name}</h2><p className="text-sm font-bold text-stone-500">{product.categories?.name ?? "Categoria indisponível"} · {product.price === null ? "Sem preço" : `R$ ${Number(product.price).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}`} · ordem {product.sort_order}</p></div><div className="flex gap-2"><span className={`rounded-full px-3 py-1 text-xs font-black ${product.is_active ? "bg-green-100 text-green-800" : "bg-stone-200 text-stone-700"}`}>{product.is_active ? "Ativo" : "Inativo"}</span>{product.is_featured && <span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-black text-orange-800">Destaque</span>}</div></div><form action={action} className="space-y-4"><ProductFields product={product} categories={categories} state={state} /><FormFeedback state={state} /><button className="btn btn-primary w-full sm:w-auto" disabled={pending}>{pending ? "Salvando…" : "Salvar edição"}</button></form><div className="my-4 h-px bg-stone-200" /><ProductImageEditor product={product} imageUrl={imageUrl} /><div className="my-4 h-px bg-stone-200" /><ProductActions product={product} /></article>; }
