"use server";
/* eslint-disable @typescript-eslint/no-unused-vars -- action-state signatures require the previous state */
import { revalidatePath } from "next/cache";
import { createGalleryImage, deleteGalleryImage, getAdminGalleryImage, toggleGalleryPublished, updateGalleryImagePosition, updateGalleryMetadata, updateGalleryStoragePath } from "@/data/repositories/gallery.repository";
import { parseImagePosition } from "@/lib/image-position";
import { requireAdmin } from "@/features/admin/auth/server";
import type { AdminActionResult } from "@/features/admin/mutations/types";
import { UUID_PATTERN } from "@/features/admin/products/validation";
import { removeGalleryImageFile, uploadedImageDiagnostic, uploadedImageErrorMessage, verifyGalleryUpload } from "@/lib/storage/admin-site-assets";
import { createClient } from "@/lib/supabase/server";
import { GALLERY_PATH_PATTERN, validateGalleryMetadata } from "./validation";
const refresh = () => { revalidatePath("/"); revalidatePath("/admin"); revalidatePath("/admin/gallery"); };
function failure(error: unknown): AdminActionResult { console.error("Falha em mutação da galeria.", { name: error instanceof Error ? error.name : "unknown", ...uploadedImageDiagnostic(error) }); return { ok: false, message: uploadedImageErrorMessage(error) ?? "Não foi possível concluir a operação na galeria. Tente novamente." }; }
async function cleanupNewGalleryFile(client: Awaited<ReturnType<typeof createClient>>, storagePath: string) { try { await removeGalleryImageFile(client, storagePath); } catch (error) { console.error("Arquivo novo da galeria requer limpeza.", { name: error instanceof Error ? error.name : "unknown" }); } }
export async function createGalleryImageAction(storagePath: string, _previous: AdminActionResult, data: FormData): Promise<AdminActionResult> { await requireAdmin(); if (!GALLERY_PATH_PATTERN.test(storagePath)) return { ok: false, message: "Arquivo da galeria inválido." }; const validation = validateGalleryMetadata(data); const client = await createClient(); if (!validation.values) { await cleanupNewGalleryFile(client, storagePath); return { ok: false, message: "Revise os campos destacados.", fieldErrors: validation.fieldErrors }; } try { await verifyGalleryUpload(client, storagePath); await createGalleryImage(client, storagePath, validation.values); refresh(); return { ok: true, message: "Imagem adicionada com sucesso." }; } catch (error) { await cleanupNewGalleryFile(client, storagePath); return failure(error); } }
export async function updateGalleryMetadataAction(id: string, _previous: AdminActionResult, data: FormData): Promise<AdminActionResult> { await requireAdmin(); if (!UUID_PATTERN.test(id)) return { ok: false, message: "Imagem inválida." }; const validation = validateGalleryMetadata(data); if (!validation.values) return { ok: false, message: "Revise os campos destacados.", fieldErrors: validation.fieldErrors }; const client = await createClient(); try { if (!await getAdminGalleryImage(client, id)) return { ok: false, message: "Imagem não encontrada." }; await updateGalleryMetadata(client, id, validation.values); refresh(); return { ok: true, message: "Dados da imagem atualizados." }; } catch (error) { return failure(error); } }
export async function replaceGalleryImageAction(id: string, newPath: string): Promise<AdminActionResult> { await requireAdmin(); if (!UUID_PATTERN.test(id) || !GALLERY_PATH_PATTERN.test(newPath)) return { ok: false, message: "Imagem inválida." }; const client = await createClient(); try { const current = await getAdminGalleryImage(client, id); if (!current) { await removeGalleryImageFile(client, newPath); return { ok: false, message: "Imagem não encontrada." }; } await verifyGalleryUpload(client, newPath); try { await updateGalleryStoragePath(client, id, newPath); } catch (error) { await removeGalleryImageFile(client, newPath); throw error; } try { await removeGalleryImageFile(client, current.storage_path); } catch (error) { console.error("Arquivo antigo da galeria requer limpeza.", { name: error instanceof Error ? error.name : "unknown" }); } refresh(); return { ok: true, message: "Imagem substituída com sucesso." }; } catch (error) { return failure(error); } }
export async function toggleGalleryAction(id: string, published: boolean, _previous: AdminActionResult): Promise<AdminActionResult> { await requireAdmin(); if (!UUID_PATTERN.test(id)) return { ok: false, message: "Imagem inválida." }; const client = await createClient(); try { if (!await getAdminGalleryImage(client, id)) return { ok: false, message: "Imagem não encontrada." }; await toggleGalleryPublished(client, id, published); refresh(); return { ok: true, message: published ? "Imagem publicada." : "Imagem despublicada." }; } catch (error) { return failure(error); } }
export async function deleteGalleryImageAction(id: string, _previous: AdminActionResult): Promise<AdminActionResult> { await requireAdmin(); if (!UUID_PATTERN.test(id)) return { ok: false, message: "Imagem inválida." }; const client = await createClient(); try { const current = await getAdminGalleryImage(client, id); if (!current) return { ok: false, message: "Imagem não encontrada." }; await deleteGalleryImage(client, id); try { await removeGalleryImageFile(client, current.storage_path); } catch (error) { console.error("Arquivo órfão da galeria requer limpeza.", { name: error instanceof Error ? error.name : "unknown" }); refresh(); return { ok: true, message: "Registro excluído; o arquivo requer limpeza posterior." }; } refresh(); return { ok: true, message: "Imagem e arquivo excluídos." }; } catch (error) { return failure(error); } }
export async function updateGalleryImagePositionAction(id: string, x: number, y: number): Promise<AdminActionResult> { await requireAdmin(); if (!UUID_PATTERN.test(id)) return { ok: false, message: "Imagem inválida." }; const position = parseImagePosition(x, y); if (!position) return { ok: false, message: "Posição inválida. Use valores inteiros entre 0 e 100." }; const client = await createClient(); try { if (!await getAdminGalleryImage(client, id)) return { ok: false, message: "Imagem não encontrada." }; await updateGalleryImagePosition(client, id, position.x, position.y); refresh(); return { ok: true, message: "Enquadramento salvo." }; } catch (error) { return failure(error); } }
