import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ requireAdmin: vi.fn(), revalidatePath: vi.fn(), createClient: vi.fn(async () => ({})), createGalleryImage: vi.fn(), updateGalleryMetadata: vi.fn(), toggleGalleryPublished: vi.fn(), updateGalleryStoragePath: vi.fn(), deleteGalleryImage: vi.fn(), getAdminGalleryImage: vi.fn(), verifyGalleryUpload: vi.fn(), removeGalleryImageFile: vi.fn() }));
vi.mock("next/cache", () => ({ revalidatePath: mocks.revalidatePath })); vi.mock("@/features/admin/auth/server", () => ({ requireAdmin: mocks.requireAdmin })); vi.mock("@/lib/supabase/server", () => ({ createClient: mocks.createClient })); vi.mock("@/lib/storage/admin-site-assets", () => ({ verifyGalleryUpload: mocks.verifyGalleryUpload, removeGalleryImageFile: mocks.removeGalleryImageFile })); vi.mock("@/data/repositories/gallery.repository", () => ({ createGalleryImage: mocks.createGalleryImage, updateGalleryMetadata: mocks.updateGalleryMetadata, toggleGalleryPublished: mocks.toggleGalleryPublished, updateGalleryStoragePath: mocks.updateGalleryStoragePath, deleteGalleryImage: mocks.deleteGalleryImage, getAdminGalleryImage: mocks.getAdminGalleryImage }));
import { createGalleryImageAction, deleteGalleryImageAction, replaceGalleryImageAction, toggleGalleryAction, updateGalleryMetadataAction } from "./actions";
const id = "20000000-0000-4000-8000-000000000001"; const oldPath = "gallery/30000000-0000-4000-8000-000000000001.webp"; const newPath = "gallery/40000000-0000-4000-8000-000000000001.webp"; const previous = { ok: true as const, message: "" };
function form() { const data = new FormData(); Object.entries({ altText: "Pet após banho", caption: "Pronto", sortOrder: "2", isPublished: "on" }).forEach(([key, value]) => data.set(key, value)); return data; }
describe("gallery actions", () => { beforeEach(() => { vi.clearAllMocks(); mocks.getAdminGalleryImage.mockResolvedValue({ id, storage_path: oldPath }); });
  it("verifies upload, creates metadata and revalidates", async () => { await expect(createGalleryImageAction(newPath, previous, form())).resolves.toMatchObject({ ok: true }); expect(mocks.verifyGalleryUpload).toHaveBeenCalledWith({}, newPath); expect(mocks.createGalleryImage).toHaveBeenCalledWith({}, newPath, expect.objectContaining({ alt_text: "Pet após banho" })); for (const path of ["/", "/admin", "/admin/gallery"]) expect(mocks.revalidatePath).toHaveBeenCalledWith(path); });
  it("cleans the upload when insert fails", async () => { mocks.createGalleryImage.mockRejectedValueOnce(new Error("insert")); await expect(createGalleryImageAction(newPath, previous, form())).resolves.toMatchObject({ ok: false }); expect(mocks.removeGalleryImageFile).toHaveBeenCalledWith({}, newPath); });
  it("replaces in safe order and cleans the new file when update fails", async () => { await replaceGalleryImageAction(id, newPath); expect(mocks.updateGalleryStoragePath.mock.invocationCallOrder[0]).toBeLessThan(mocks.removeGalleryImageFile.mock.invocationCallOrder[0]); expect(mocks.removeGalleryImageFile).toHaveBeenCalledWith({}, oldPath); vi.clearAllMocks(); mocks.getAdminGalleryImage.mockResolvedValue({ id, storage_path: oldPath }); mocks.updateGalleryStoragePath.mockRejectedValueOnce(new Error("update")); await replaceGalleryImageAction(id, newPath); expect(mocks.removeGalleryImageFile).toHaveBeenCalledWith({}, newPath); });
  it("updates metadata, toggles, deletes DB then file and enforces auth", async () => { await updateGalleryMetadataAction(id, previous, form()); await toggleGalleryAction(id, false, previous); await deleteGalleryImageAction(id, previous); expect(mocks.updateGalleryMetadata).toHaveBeenCalledOnce(); expect(mocks.toggleGalleryPublished).toHaveBeenCalledWith({}, id, false); expect(mocks.deleteGalleryImage.mock.invocationCallOrder[0]).toBeLessThan(mocks.removeGalleryImageFile.mock.invocationCallOrder[0]); mocks.requireAdmin.mockRejectedValueOnce(new Error("NEXT_REDIRECT")); await expect(deleteGalleryImageAction(id, previous)).rejects.toThrow("NEXT_REDIRECT"); });
  it("rejects browser-supplied arbitrary paths", async () => { await expect(createGalleryImageAction("products/hack.webp", previous, form())).resolves.toMatchObject({ ok: false }); expect(mocks.verifyGalleryUpload).not.toHaveBeenCalled(); });
});
