"use client";
import Image from "next/image";
import { useActionState, useEffect, useRef, useState } from "react";
import type { FormEvent } from "react";
import type { GalleryImageRow } from "@/data/repositories/gallery.repository";
import { FieldError, FormFeedback } from "@/features/admin/components/form-feedback";
import { initialAdminActionResult, type AdminActionResult } from "@/features/admin/mutations/types";
import { optimizeImage, optimizedFilename, type OptimizedImage } from "@/lib/images/optimize-image";
import { SITE_ASSETS_BUCKET } from "@/lib/storage/site-assets";
import { createClient } from "@/lib/supabase/client";
import { createGalleryImageAction, deleteGalleryImageAction, replaceGalleryImageAction, toggleGalleryAction, updateGalleryMetadataAction } from "./actions";
import { prepareGallerySubmission } from "./gallery-submit";
const inputClass = "field mt-1"; const bytes = (value: number) => value < 1024 * 1024 ? `${Math.round(value / 1024)} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`;
function MetadataFields({ image, state }: { image?: GalleryImageRow; state: AdminActionResult }) { return <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-extrabold text-olive sm:col-span-2">Texto alternativo<input className={inputClass} name="altText" defaultValue={image?.alt_text} maxLength={300} required /><FieldError state={state} name="altText" /></label><label className="text-sm font-extrabold text-olive sm:col-span-2">Legenda <span className="font-semibold text-stone-500">(opcional)</span><textarea className={`${inputClass} min-h-24`} name="caption" defaultValue={image?.caption ?? ""} maxLength={1000} /><FieldError state={state} name="caption" /></label><label className="text-sm font-extrabold text-olive">Ordem<input className={inputClass} name="sortOrder" type="number" min="0" step="1" defaultValue={image?.sort_order ?? 0} required /><FieldError state={state} name="sortOrder" /></label><label className="flex min-h-11 items-center gap-2 self-end rounded-xl bg-stone-50 px-3 font-extrabold text-olive"><input name="isPublished" type="checkbox" defaultChecked={image?.is_published ?? true} />Publicada no site</label></div>; }
function ImagePicker({ onReady, disabled }: { onReady: (image: OptimizedImage | null, preview: string | null) => void; disabled?: boolean }) { const [status, setStatus] = useState(""); const previewRef = useRef<string | null>(null); useEffect(() => () => { if (previewRef.current) URL.revokeObjectURL(previewRef.current); }, []); async function select(file?: File) { if (previewRef.current) URL.revokeObjectURL(previewRef.current); previewRef.current = null; onReady(null, null); if (!file) return; setStatus("Otimizando imagem…"); try { const optimized = await optimizeImage(file); const preview = URL.createObjectURL(optimized.file); previewRef.current = preview; onReady(optimized, preview); setStatus(`Original: ${bytes(optimized.originalBytes)} · Otimizada: ${bytes(optimized.optimizedBytes)} · ${optimized.width} × ${optimized.height}`); } catch (error) { setStatus(error instanceof Error ? error.message : "Não foi possível otimizar a imagem."); } } return <div><label className="text-sm font-extrabold text-olive">Imagem<input className={inputClass} type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={disabled} onChange={(event) => void select(event.target.files?.[0])} /></label><p className="mt-2 text-sm font-semibold text-stone-600" role="status" aria-live="polite">{status || "JPEG, PNG, WebP ou AVIF; original de até 20 MiB."}</p></div>; }
async function upload(image: OptimizedImage) { const path = optimizedFilename(image.mimeType); const { error } = await createClient().storage.from(SITE_ASSETS_BUCKET).upload(path, image.file, { contentType: image.mimeType, upsert: false }); if (error) throw new Error("Não foi possível enviar a imagem. Confirme sua sessão e tente novamente."); return path; }
export function NewGalleryForm() { const [optimized, setOptimized] = useState<OptimizedImage | null>(null); const [preview, setPreview] = useState<string | null>(null); const [state, setState] = useState<AdminActionResult>(initialAdminActionResult); const [pending, setPending] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!optimized) { setState({ ok: false, message: "Selecione e aguarde a otimização da imagem." }); return; } const submission = prepareGallerySubmission(event.currentTarget, optimized); setPending(true); setState({ ok: true, message: "Enviando…" }); try { const path = await upload(submission.image); setState(await createGalleryImageAction(path, initialAdminActionResult, submission.formData)); } catch (error) { setState({ ok: false, message: error instanceof Error ? error.message : "Falha no envio." }); } finally { setPending(false); } } return <section id="nova-imagem" className="mb-6 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6"><h2 className="mb-4 text-xl font-black text-olive">Adicionar foto</h2><form onSubmit={submit} className="space-y-4"><ImagePicker disabled={pending} onReady={(value, url) => { setOptimized(value); setPreview(url); }} />{preview && <Image src={preview} alt="Prévia da imagem otimizada" width={480} height={320} unoptimized className="max-h-72 w-full rounded-xl object-contain bg-stone-100" />}<MetadataFields state={state} /><FormFeedback state={state} /><button className="btn btn-primary w-full sm:w-auto" disabled={pending || !optimized}>{pending ? "Enviando…" : "Adicionar à galeria"}</button></form></section>; }
function ReplacePicker({ id }: { id: string }) { const [optimized, setOptimized] = useState<OptimizedImage | null>(null); const [preview, setPreview] = useState<string | null>(null); const [state, setState] = useState<AdminActionResult>(initialAdminActionResult); const [pending, setPending] = useState(false); async function replace() { if (!optimized) return; setPending(true); try { const path = await upload(optimized); setState(await replaceGalleryImageAction(id, path)); } catch (error) { setState({ ok: false, message: error instanceof Error ? error.message : "Falha no envio." }); } finally { setPending(false); } } return <div className="space-y-3 rounded-xl bg-stone-50 p-3"><h3 className="font-black text-olive">Substituir arquivo</h3><ImagePicker disabled={pending} onReady={(value, url) => { setOptimized(value); setPreview(url); }} />{preview && <Image src={preview} alt="Prévia da nova imagem otimizada" width={320} height={220} unoptimized className="max-h-52 w-full rounded-lg object-contain" />}<button type="button" className="btn btn-secondary" disabled={pending || !optimized} onClick={() => void replace()}>{pending ? "Enviando…" : "Substituir imagem"}</button><FormFeedback state={state} /></div>; }
export function GalleryCard({ image, imageUrl }: { image: GalleryImageRow; imageUrl: string }) { const [state, action, pending] = useActionState(updateGalleryMetadataAction.bind(null, image.id), initialAdminActionResult); const [toggleState, toggleAction, toggling] = useActionState(toggleGalleryAction.bind(null, image.id, !image.is_published), initialAdminActionResult); const [deleteState, deleteAction, deleting] = useActionState(deleteGalleryImageAction.bind(null, image.id), initialAdminActionResult); const [confirming, setConfirming] = useState(false); return <article className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6"><Image src={imageUrl} alt={image.alt_text} width={640} height={420} className="mb-4 h-56 w-full rounded-xl object-cover" /><div className="mb-4 flex justify-between gap-2"><p className="font-black text-olive">Ordem {image.sort_order}</p><span className={`rounded-full px-3 py-1 text-xs font-black ${image.is_published ? "bg-green-100 text-green-800" : "bg-stone-200 text-stone-700"}`}>{image.is_published ? "Publicada" : "Não publicada"}</span></div><form action={action} className="space-y-4"><MetadataFields image={image} state={state} /><FormFeedback state={state} /><button className="btn btn-primary w-full sm:w-auto" disabled={pending}>{pending ? "Salvando…" : "Salvar dados"}</button></form><div className="my-4 h-px bg-stone-200" /><ReplacePicker id={image.id} /><div className="mt-4 flex flex-wrap gap-2"><form action={toggleAction}><button className="btn btn-secondary" disabled={toggling}>{toggling ? "Alterando…" : image.is_published ? "Despublicar" : "Publicar"}</button></form>{confirming ? <><form action={deleteAction}><button className="btn bg-red-700 text-white" disabled={deleting}>{deleting ? "Excluindo…" : "Excluir foto e arquivo"}</button></form><button type="button" className="btn btn-secondary" onClick={() => setConfirming(false)}>Cancelar</button></> : <button type="button" className="btn border border-red-200 bg-white text-red-700" onClick={() => setConfirming(true)}>Excluir</button>}</div><FormFeedback state={toggleState.message ? toggleState : deleteState} />{confirming && <p role="alert" className="mt-2 text-sm font-bold text-red-700">Confirmar exclusão permanente de “{image.alt_text}” e do arquivo correspondente? Esta ação não pode ser desfeita.</p>}</article>; }
