"use client";

import { useActionState } from "react";
import type { BusinessSettingsRow } from "@/data/repositories/business.repository";
import { FieldError, FormFeedback } from "@/features/admin/components/form-feedback";
import { initialAdminActionResult } from "@/features/admin/mutations/types";
import { updateHomeContentAction } from "./actions";

function Field({ label, name, value, maxLength, state, area = false, optional = false }: { label: string; name: string; value: string | null; maxLength: number; state: typeof initialAdminActionResult; area?: boolean; optional?: boolean }) {
  const input = area ? <textarea className="field mt-1" name={name} defaultValue={value ?? ""} maxLength={maxLength} rows={3} required={!optional} /> : <input className="field mt-1" name={name} defaultValue={value ?? ""} maxLength={maxLength} required={!optional} />;
  return <label className="block text-sm font-extrabold text-olive">{label}{optional && <span className="font-semibold text-stone-500"> (opcional)</span>}{input}<FieldError state={state} name={name} /></label>;
}

export function ContentForm({ row }: { row: BusinessSettingsRow }) {
  const [state, action, pending] = useActionState(updateHomeContentAction.bind(null, row.id), initialAdminActionResult);
  return <form action={action} className="space-y-6"><FormFeedback state={state} />
    <section className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6"><h2 className="text-xl font-black text-olive">Hero</h2><p className="mb-4 mt-1 text-sm font-semibold text-stone-600">Os botões continuam levando ao agendamento e aos serviços.</p><div className="grid gap-4 sm:grid-cols-2"><Field label="Título" name="heroTitle" value={row.hero_title} maxLength={120} state={state} /><Field label="Trecho em destaque" name="heroHighlight" value={row.hero_highlight} maxLength={60} state={state} /><div className="sm:col-span-2"><Field area label="Descrição" name="heroDescription" value={row.hero_description} maxLength={400} state={state} /></div><Field label="Texto do botão principal" name="heroPrimaryCta" value={row.hero_primary_cta} maxLength={60} state={state} /><Field label="Texto do botão secundário" name="heroSecondaryCta" value={row.hero_secondary_cta} maxLength={60} state={state} /></div></section>
    <section className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6"><h2 className="mb-4 text-xl font-black text-olive">Sobre</h2><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Título" name="aboutTitle" value={row.about_title} maxLength={160} state={state} /></div><div className="sm:col-span-2"><Field area label="Texto institucional" name="aboutDescription" value={row.about_description} maxLength={1000} state={state} /></div><Field label="Primeiro diferencial" name="aboutFeatureOneTitle" value={row.about_feature_one_title} maxLength={100} state={state} /><Field label="Segundo diferencial" name="aboutFeatureTwoTitle" value={row.about_feature_two_title} maxLength={100} state={state} /></div></section>
    <section className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6"><h2 className="mb-4 text-xl font-black text-olive">Footer e contato</h2><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Field area label="Descrição institucional" name="footerDescription" value={row.footer_description} maxLength={400} state={state} /></div><Field label="Título de contato" name="footerContactTitle" value={row.footer_contact_title} maxLength={80} state={state} /><Field label="Título de localização" name="footerLocationTitle" value={row.footer_location_title} maxLength={80} state={state} /></div></section>
    <section className="rounded-2xl border border-stone-200 bg-white p-4 shadow-sm sm:p-6"><h2 className="text-xl font-black text-olive">TaxiPet</h2><p className="mb-4 mt-1 text-sm font-semibold text-stone-600">Disponibilidade, descrição e preço continuam sendo definidos no cadastro do serviço TaxiPet.</p><div className="grid gap-4 sm:grid-cols-2"><Field label="Título" name="taxipetTitle" value={row.taxipet_title} maxLength={160} state={state} /><Field label="Texto do botão" name="taxipetCta" value={row.taxipet_cta} maxLength={60} state={state} /><Field optional label="Região atendida" name="taxipetRegion" value={row.taxipet_region} maxLength={160} state={state} /><Field optional label="Observação" name="taxipetNote" value={row.taxipet_note} maxLength={400} state={state} /></div></section>
    <button className="btn btn-primary w-full sm:w-auto" disabled={pending}>{pending ? "Salvando…" : "Salvar conteúdo"}</button>
  </form>;
}
